name: Deploy

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: 3.1.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Publish projects
      run: dotnet publish -c Release

    - name: Upload artifact (webapp)
      uses: actions/upload-artifact@v2
      with:
        name: webapp-test-1
        path: WebApplication1/*.zip

    - name: Upload artifact (function)
      uses: actions/upload-artifact@v2
      with:
        name: function-test-2
        path: FunctionApp1/*.zip

  deploy-all:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        app: [webapp-test-1, function-test-2]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.app }}
        path: publish
  
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: Deploy to Dev
      run: az webapp deployment source config-zip -r DeployTest-RG -n ${{ matrix.app }} --src ./publish/*.zip