name: Production

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: 3.1.x
  AZURE_WEB_APP_NAME: webapp-deploytest-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Publish projects
      run: dotnet publish -c Release

    - name: Upload artifact (webapp)
      uses: actions/upload-artifact@v2
      with:
        name: webapp
        path: WebApplication1/*.zip

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ env.AZURE_WEB_APP_NAME }}.azurewebsites.net
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: webapp

    - name: Deploy production
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEB_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: ./WebApplication1.zip