name: Staging

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build projects
      run: dotnet build -c Release

    - name: Test projects
      run: dotnet test -c Release
      if: contains(github.event.pull_request.labels.*.name, 'full-ci')

