name: Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

env:
  DOTNET_VERSION: 3.1.x
  AZURE_WEB_APP_NAME: webapp-deploytest-1
  AZURE_RESOURCE_GROUP_NAME: deploytest-rg

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Publish projects
      run: dotnet publish -c Release

    - name: Upload artifact (webapp)
      uses: actions/upload-artifact@v2
      with:
        name: webapp
        path: WebApplication1/*.zip

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://webapp-deploytest-1-pr-${{ github.event.number }}.azurewebsites.net
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: webapp

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create staging slot
      run: az webapp deployment slot create -n ${{ env.AZURE_WEB_APP_NAME }} -g ${{ env.AZURE_RESOURCE_GROUP_NAME }} -s pr-${{ github.event.number }} --configuration-source production

    - name: Deploy staging
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEB_APP_NAME }}
        slot-name: pr-${{ github.event.number }}
        package: ./WebApplication1.zip

  delete-slot:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Delete staging slot
      run: az webapp deployment slot delete -n ${{ env.AZURE_WEB_APP_NAME }} -g ${{ env.AZURE_RESOURCE_GROUP_NAME }} -s pr-${{ github.event.number }}