name: Deploy

on:
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: 3.1.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Publish projects
      run: dotnet publish -c Release

    - name: Upload artifact (webapp)
      uses: actions/upload-artifact@v2
      with:
        name: webapp
        path: WebApplication1/*.zip

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://webapp-deploytest-1-staging.azurewebsites.net
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: webapp

    - name: Deploy staging
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        slot-name: ${{ secrets.AZURE_WEBAPP_SLOT_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: ./WebApplication1.zip